import Head from "next/head";
import { Inter } from "next/font/google";
import { useEffect } from "react";
import {
  Box,
  Center,
  Flex,
  Heading,
  Link,
  Text,
  useMediaQuery,
} from "@chakra-ui/react";
import theme from "@/styles/root";
import MobileMenu from "@/components/mobileMenu";
import Navigation from "@/components/sections/Nav";
import RigthBar from "@/components/parts/rigthBar";
import LeftBar from "@/components/parts/lefBar";
import CenterPart from "@/components/parts/CenterPart";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const appStoreColor = "red";
  const [isLargerThan768] = useMediaQuery("(min-width: 800px)");
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* le header  */}
      <Center
        w={"100%"}
        h={"8vh"}
        position={{ base: "fixed", md: "relative" }}
        bg={theme.navy}
        zIndex={"banner"}
      >
        <Flex
          w={"95%"}
          h={"100%"}
          alignItems={"center"}
          justifyContent={"space-between"}
        >
          {/* logo  */}
          <Link
            h={"100%"}
            w={"auto"}
            display={"flex"}
            justifyContent={"center"}
            alignItems={"center"}
          >
            <Heading color={theme.green} fontSize={"2xl"}>
              KOD
            </Heading>
          </Link>

          {/* le button du menu  */}
          {isLargerThan768 ? <Navigation /> : <MobileMenu />}
        </Flex>
      </Center>

      {/* le corps  */}
      <Flex w={"100%"} minH={"92vh"} flexDirection={"row"} bg={theme.navy}>
        <LeftBar />
        <CenterPart />
        <RigthBar />
      </Flex>

      {/* footer  */}
    </>
  );
}
